"""init

Revision ID: 5c6c010cb60c
Revises: 
Create Date: 2026-02-21 18:24:07.039388
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '5c6c010cb60c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=300), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('proxy_profile', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_keyword'), 'keywords', ['keyword'], unique=False)
    op.create_index(op.f('ix_keywords_proxy_profile'), 'keywords', ['proxy_profile'], unique=False)
    op.create_index(op.f('ix_keywords_region'), 'keywords', ['region'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_kind'), 'runs', ['kind'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('watch_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('proxy_profile', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_watch_urls_proxy_profile'), 'watch_urls', ['proxy_profile'], unique=False)
    op.create_index(op.f('ix_watch_urls_region'), 'watch_urls', ['region'], unique=False)
    op.create_table('page_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('watch_url_id', sa.Integer(), nullable=False),
    sa.Column('canonical', sa.String(length=1000), nullable=True),
    sa.Column('hreflang', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['watch_url_id'], ['watch_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_tags_run_id'), 'page_tags', ['run_id'], unique=False)
    op.create_index(op.f('ix_page_tags_watch_url_id'), 'page_tags', ['watch_url_id'], unique=False)
    op.create_table('serp_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=1000), nullable=False),
    sa.Column('snippet', sa.String(length=2000), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serp_results_keyword_id'), 'serp_results', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_serp_results_position'), 'serp_results', ['position'], unique=False)
    op.create_index(op.f('ix_serp_results_run_id'), 'serp_results', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serp_results_run_id'), table_name='serp_results')
    op.drop_index(op.f('ix_serp_results_position'), table_name='serp_results')
    op.drop_index(op.f('ix_serp_results_keyword_id'), table_name='serp_results')
    op.drop_table('serp_results')
    op.drop_index(op.f('ix_page_tags_watch_url_id'), table_name='page_tags')
    op.drop_index(op.f('ix_page_tags_run_id'), table_name='page_tags')
    op.drop_table('page_tags')
    op.drop_index(op.f('ix_watch_urls_region'), table_name='watch_urls')
    op.drop_index(op.f('ix_watch_urls_proxy_profile'), table_name='watch_urls')
    op.drop_table('watch_urls')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_kind'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_keywords_region'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_proxy_profile'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_keyword'), table_name='keywords')
    op.drop_table('keywords')
    # ### end Alembic commands ###
